#! /bin/bash

cat to_stow | xargs stow
# if [[ -z $STOW_FOLDERS]]; then
#   STOW_FOLDERS="alacritty,flutter,nvim,scripts,tmux,git,picom,polybar,snippets,zsh"
# fi
#
# if [[ -z $DOTFILES ]]; then
#   DOTFILES=$HOME/.dotfiles
# fi
#
# STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
#
